version: "3.8"

services:
  apiserver:
    build:
      context: .
      target: dev
    image: kvdomingo/wagtail-demo-api:latest
    env_file: .env
    volumes:
      - .:/wag
      - ./db.sqlite3:/wag/db.sqlite3

#  frontend:
#    build:
#      context: ./web/app
#      target: dev
#    image: kvdomingo/wagtail-demo-web:latest
#    env_file: .web/app/.env
#    volumes:
#      - ./web/app:/web

  proxy:
    image: nginx:latest
    ports:
      - 8000:8000
    command:
      - nginx
      - "-g"
      - daemon off;
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apiserver
    restart: unless-stopped
